spring:
  application:
    name: Blood-sample-management-api
  datasource:
    username: root
    password: Varun@123
    url: jdbc:mysql://localhost:3306/bsm_db?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
